dt_user_accueil:
    pattern:   /
    defaults: { _controller: DTUserBundle:Security:index}

login:
    pattern: /login
    defaults: { _controller: DTUserBundle:Security:login}
    
dt_user_mes_doctorants:
    pattern: /mes_doctorants
    defaults: { _controller: DTUserBundle:User:mesDoctorants}
    
dt_user_doctorant_labo:
    pattern: /doctorant_labo
    defaults: { _controller: DTUserBundle:User:doctorantLabo}
