dt_doctorama_accueil:
    pattern:   /
    defaults: { _controller: DTDoctoramaBundle:Doctorama:index}
    #defaults: { _controller: DTDoctoramaBundle:Security:index}
    
dt_doctorama_mes_doctorants:
    pattern: /encadrant/mes_doctorants
    defaults: { _controller: DTDoctoramaBundle:Doctorama:mesDoctorants}
    
dt_doctorama_doctorant_labo:
    pattern: /encadrant/doctorant_labo
    defaults: { _controller: DTDoctoramaBundle:Doctorama:doctorantLabo}

dt_doctorama_agenda:
    pattern: /agenda
    defaults: { _controller: DTDoctoramaBundle:Doctorama:agenda}
    
dt_doctorama_statistiques:
    pattern: /statistiques
    defaults: {  _controller: DTDoctoramaBundle:Doctorama:statistiques}

dt_doctorama_historique_doctorants:
    pattern: /encadrant/historique_doctorants
    defaults: {  _controller: DTDoctoramaBundle:Doctorama:historiqueDoctorants}
    
dt_doctorama_index:
    pattern:   /index
    defaults: { _controller: DTDoctoramaBundle:Doctorama:index}

dt_doctorama_admin_dossier_suivis:
    pattern: /encadrant/dossier_suivis
    defaults: { _controller: DTDoctoramaBundle:Doctorama:adminDossierSuivis}
    
dt_doctorama_creer_dossier_suivis:
    pattern: /encadrant/doctorant_labo/creer_dossier_suivis
    defaults: { _controller: DTDoctoramaBundle:Doctorama:creerDossierSuivis}
    
dt_doctorama_modif_dossier_suivis:
    pattern: /encadrant/doctorant_labo/modif_dossier_suivis/{id_doctorant}
    defaults: { _controller: DTDoctoramaBundle:Doctorama:modifDossierSuivis}

dt_detail_doctorant:
    pattern: /detail_doctorant/{id_doctorant}
    defaults: { _controller: DTDoctoramaBundle:Doctorama:detailDoctorant}

dt_formulaire_creation_dossier:
    pattern: /creation_dossier_suivis
    defaults: { _controller: DTDoctoramaBundle:Doctorama:creationDossier}