# src/DT/UtilisateurBundle/Resources/config/routing.yml

dt_utilisateur_home:
    path:     /
    defaults: { _controller: DTUtilisateurBundle:Advert:index }
    
dt_utilisateur_view:
    path:    /advert/{id}
    defaults: { _controller: DTUtilisateurBundle:Advert:view }
    
dt_utilisateur_view_slug:
    path:     /{year}/{slug}.{_format}
    defaults: { _controller: DTUtilisateurBundle:Advert:viewSlug, _format : html}
    requirements:
        year: \d{4}
        _format: html|xml
    
dt_utilisateur_add:
    path:     /add
    defaults: { _controller: DTUtilisateurBundle:Advert:add }
    
